name: CI/CD Deployment to AWS EC2

on:
  push:
    branches:
      - main  # Ganti master jika branch kamu namanya master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/klinikpemweb
            git fetch --all
            git reset --hard origin/main
            # Memastikan file .env tetap aman jika tidak masuk git
            sudo docker-compose down
            sudo docker system prune -f
            sudo docker-compose up -d --build
